[package]
name = "sudoku"
version = "0.1.0"
edition = "2024"

[lib]
name = "sudoku_lib"
path = "src/lib.rs"

[dependencies]
rand = "0.9.2"
clap = { version = "4.5", features = ["derive"] }
ratatui = "0.30.0"
crossterm = "0.29.0"
